# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.24
_src_path: https://github.com/OCA/oca-addons-repo-template.git
additional_ruff_rules: []
ci: GitHub
convert_readme_fragments_to_markdown: true
generate_requirements_txt: true
github_check_license: true
github_ci_extra_env: {}
github_enable_codecov: true
github_enable_makepot: true
github_enable_stale_action: true
github_enforce_dev_status_compatibility: true
include_wkhtmltopdf: false
odoo_test_flavor: Both
odoo_version: 17.0
org_name: Treming
org_slug: Treming
rebel_module_groups: []
repo_description: project to create reporting to track time and price recieve packing
repo_name: project to technical test that create a module to calculate time to recieve
    packing
repo_slug: treming_tecnical_test
repo_website: https://github.com/Treming/treming_tecnical_test
use_pyproject_toml: true
use_ruff: true

